UPDATE.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -317,17 +317,14 @@ jobs:
       - run:
         name: create .env file
         command: |
-          cd backend
-          touch .env
-          export ENVFILE=/home/circleci/project/backend/.env
-          echo TYPEORM_DATABASE=postgres > $ENVFILE
-          echo TYPEORM_ENTITIES=/home/ubuntu/backend/src/modules/domain/**/*.entity.ts > $ENVFILE
-          echo TYPEORM_HOST=database-2.cb5nbzqyh6zq.us-east-1.rds.amazonaws.com >  $ENVFILE
-          echo TYPEORM_MIGRATIONS=/home/ubuntu/backend/src/migrations/*.ts > $ENVFILE
-          echo TYPEORM_MIGRATIONS_DIR=/home/ubuntu/backend/src/migrations/ > $ENVFILE
-          echo TYPEORM_PASSWORD=WdCdmxP9738PoV > $ENVFILE
-          echo TYPEORM_PORT=5432 > $ENVFILE
-          echo TYPEORM_USERNAME=postgres > $ENVFILE
+          echo TYPEORM_DATABASE=postgres > ~/backend/.env
+          echo TYPEORM_ENTITIES=/home/ubuntu/backend/src/modules/domain/**/*.entity.ts >> ~/backend/.env
+          echo TYPEORM_HOST=database-2.cb5nbzqyh6zq.us-east-1.rds.amazonaws.com >> ~/backend/.env
+          echo TYPEORM_MIGRATIONS=/home/ubuntu/backend/src/migrations/*.ts >> ~/backend/.env
+          echo TYPEORM_MIGRATIONS_DIR=/home/ubuntu/backend/src/migrations/ >> ~/backend/.env
+          echo TYPEORM_PASSWORD=WdCdmxP9738PoV >> ~/backend/.env
+          echo TYPEORM_PORT=5432 >> ~/backend/.env
+          echo TYPEORM_USERNAME=postgres >> ~/backend/.env
 
       - run:
           name: Deploy backend
@@ -354,6 +351,32 @@ jobs:
           backend_stack:  "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" 
       - revert-migrations:
           workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}" 
+
+  smoke-test:
+    docker:
+      - image: python:3.7-alpine3.11 
+    steps:
+      - checkout
+
+      - run:
+          name: Get backend url
+          command: |
+            export BACKEND_IP=$(aws ec2 describe-instances \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --output text) 
+            export API_URL="http://${BACKEND_IP}:3030"
+
+            if curl --insecure "${API_URL}/api/status" | grep "ok"
+            then
+              exit 0
+            else
+              exit 1
+            fi
+      - run:
+          name: Frontend smoke test.
+          command: |
+            # your code here
+      # Here's where you will add some code to rollback on failure
 
 workflows:
   default:
